### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by snobjorn** [teppokoivula/WireMailSwiftMailer#3]
Using ProcessWire 3.0.195 dev.
And PHP version 8.1.

I get this error:
"Compilation error: Array and string offset access syntax with curly braces is no longer supported (line 402 i site/modules/WireMailSwiftMailer/Swift-5.2.1/lib/classes/Swift/Transport/AbstractSmtpTransport.php)"

**Comment by teppokoivula** [comment]
Hey @snobjorn! This issue should be fixed in version 0.3.0 of the module.

Please note, though, that this is a pretty major upgrade, going from Swift Mailer 5 to 6. Additionally it turns out that Swift has been discontinued, so I would recommend switching to another WireMail module; this module still works, but since it's relying on a no longer maintained mailer library, it may break or cause issues in the future.

I might release a direct replacement based on Symfony Mailer at some point, but at least for now I think that WireMailSmtp is likely your best bet. Personally I've moved on to Mailgun, so I'm a bit out of touch when it comes to SMTP stuff :)
